<a href="https://colab.research.google.com/github/QaziSaim/CASE-STUDIES/blob/main/pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [2]:
print(torch.__version__)

2.9.0+cu126


In [3]:
 ### Introduction to tensor

In [4]:
# scalar
scalar =  torch.tensor(7)

In [5]:
scalar

tensor(7)

In [6]:
scalar.ndim

0

In [7]:
scalar.item()

7

In [8]:
vector = torch.tensor([3,7])

In [9]:
vector

tensor([3, 7])

In [11]:
vector.ndim

1

In [12]:
vector.shape

torch.Size([2])

In [13]:
scalar.shape

torch.Size([])

In [16]:
vector.size()

torch.Size([2])

In [22]:
MATRIX =  torch.tensor([[7,3,8],[9,1,3]])
MATRIX

tensor([[7, 3, 8],
        [9, 1, 3]])

In [23]:
MATRIX.shape

torch.Size([2, 3])

In [24]:
MATRIX.size()

torch.Size([2, 3])

In [25]:
TENSOR = torch.tensor([[1,2,3],[3,6,9],[2,4,5]])

In [26]:
TENSOR

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [27]:
TENSOR.shape

torch.Size([3, 3])

In [29]:
TENSOR.size()

torch.Size([3, 3])

In [30]:
TENSOR.ndim

2

In [32]:
random_tensor = torch.rand(size=(3,4))
print(random_tensor)

tensor([[0.8359, 0.3707, 0.4205, 0.1841],
        [0.8271, 0.0946, 0.7048, 0.9373],
        [0.4849, 0.2298, 0.5472, 0.9530]])


In [34]:
random_image = torch.rand(size=(224,224,3))
random_image.shape, random_image.size(), random_image.ndim

(torch.Size([224, 224, 3]), torch.Size([224, 224, 3]), 3)

In [36]:
zeros = torch.zeros(size=(3,4))
zeros,zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [37]:
ones = torch.ones(size=(3,4))
ones,ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [39]:
zero_to_ten_deprecated = torch.range(0, 10)
zero_to_ten_deprecated

/tmp/ipython-input-201814837.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero_to_ten_deprecated = torch.range(0, 10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [41]:
zero_to_ten = torch.arange(0,10,2)
zero_to_ten

tensor([0, 2, 4, 6, 8])

In [43]:
five_zero = torch.zeros_like(zero_to_ten)
five_zero

tensor([0, 0, 0, 0, 0])

In [44]:
five_ones = torch.ones_like(zero_to_ten)
five_ones

tensor([1, 1, 1, 1, 1])

#### Precision is the amount of detail used to describe a number.



In [46]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,
                               device=None,
                               requires_grad=False)
float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device


(torch.Size([3]), torch.float32, device(type='cpu'))

In [50]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],dtype=torch.half) #)torch.float16)
float_16_tensor.dtype

torch.float16

In [51]:
some_tensor = torch.rand(3,4)

print(some_tensor)
print(f'Shape of tensor: {some_tensor.shape}')
print(f'Datatype of tensor: {some_tensor.dtype}')
print(f'Device tensor is stored on: {some_tensor.device}')

tensor([[0.5799, 0.8165, 0.0055, 0.2349],
        [0.1719, 0.7304, 0.3723, 0.9226],
        [0.4964, 0.8297, 0.5121, 0.0998]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [52]:
tensor = torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [53]:
tensor*10

tensor([10, 20, 30])

In [54]:
tensor

tensor([1, 2, 3])

In [55]:
tensor -= 10
tensor

tensor([-9, -8, -7])

In [56]:
tensor

tensor([-9, -8, -7])

In [57]:
tensor += 10

In [58]:
tensor

tensor([1, 2, 3])

In [59]:
torch.multiply(tensor,10)

tensor([10, 20, 30])

In [60]:
tensor

tensor([1, 2, 3])

In [61]:
torch.add(tensor,10)

tensor([11, 12, 13])

In [62]:
torch.mul(tensor,tensor)

tensor([1, 4, 9])

In [63]:
tensor @ tensor

tensor(14)

In [64]:
torch.matmul(tensor,tensor)

tensor(14)

In [65]:
%%time
# Matrix multiplication by hand
# (avoid doing operations with for loops at all cost, they are computationally expensive)
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 467 µs, sys: 0 ns, total: 467 µs
Wall time: 485 µs


tensor(14)

In [66]:
%%time
torch.matmul(tensor, tensor)


CPU times: user 520 µs, sys: 0 ns, total: 520 µs
Wall time: 397 µs


tensor(14)

In [67]:
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

In [68]:
tensor_A.shape

torch.Size([3, 2])

In [69]:
tensorBA = torch.tensor([[7, 10],
                         [3,4],
                         [5,6]])

In [72]:
torch.matmul(tensor_A,tensorBA.reshape(2,3))

tensor([[15, 20, 15],
        [37, 50, 33],
        [59, 80, 51]])

In [73]:
torch.matmul(tensor_A,tensorBA.T)

tensor([[27, 11, 17],
        [61, 25, 39],
        [95, 39, 61]])

In [75]:
tensorBA.T

tensor([[ 7,  3,  5],
        [10,  4,  6]])

In [76]:
tensorBA.reshape(2,3)

tensor([[ 7, 10,  3],
        [ 4,  5,  6]])

In [77]:
tensorBA

tensor([[ 7, 10],
        [ 3,  4],
        [ 5,  6]])

In [78]:
torch.mm(tensor_A,tensorBA.T)

tensor([[27, 11, 17],
        [61, 25, 39],
        [95, 39, 61]])