<a href="https://colab.research.google.com/github/QaziSaim/CASE-STUDIES/blob/main/SDPA_Implementing_High_Performance_Transformers_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
device = 'cuda' if torch.cuda.is_available() else 'cpu'

In [3]:
query,key,value = torch.randn(2,3,8, device=device),torch.randn(2,3,8, device=device),torch.randn(2,3,8, device=device)

In [4]:
query.ndim

3

In [5]:
query.shape

torch.Size([2, 3, 8])

In [7]:
query.size()

torch.Size([2, 3, 8])

In [8]:
F.scaled_dot_product_attention(query,key,value)

tensor([[[-1.3057,  0.2999,  0.4261, -0.2526, -0.1491,  0.0753, -0.4975,
           0.1520],
         [-1.1490,  0.2964,  0.5588, -0.3852, -0.1259, -0.0453, -0.3296,
           0.1897],
         [-1.2447,  0.6172,  0.4577, -0.4879,  0.0346, -0.0931, -0.3866,
           0.2410]],

        [[-0.7513, -0.7120, -0.7856,  0.7703,  0.8148,  1.2466, -0.2571,
          -0.1547],
         [-0.4595, -1.0872, -1.0741,  0.6763, -0.1050,  0.0720, -0.0122,
          -0.5364],
         [-0.4554, -1.1269, -1.1733,  0.7477, -0.2014, -0.0852, -0.1394,
          -0.5729]]])

In [12]:
# small problem
Q = torch.tensor([1,0,0,1,1,1]).reshape(3,2)
K = torch.tensor([1,0,1,1,0,1]).reshape(3,2)
V = torch.tensor([1,0,10,0,100,5]).reshape(3,2)

In [13]:
Q,K,V

(tensor([[1, 0],
         [0, 1],
         [1, 1]]),
 tensor([[1, 0],
         [1, 1],
         [0, 1]]),
 tensor([[  1,   0],
         [ 10,   0],
         [100,   5]]))

In [15]:
Q * K

tensor([[1, 0],
        [0, 1],
        [0, 1]])

In [19]:
S = Q @ K.T

In [20]:
S

tensor([[1, 1, 0],
        [0, 1, 1],
        [1, 2, 1]])

In [23]:
dk = 2**0.5